services:
  postgres:
    image: postgres:18
    container_name: results-postgres

    environment:
      POSTGRES_DB: ResultsDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  api:
    build:
      context: ..
      dockerfile: ResultsService.Api/Dockerfile

    container_name: results-api

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=ResultsDb;Username=postgres;Password=postgres"

    ports:
      - "8080:8080"
      - "8081:8081"

    depends_on:
      - postgres

volumes:
  postgres_data: